### ISSUE TITLE
Why is seed_9 used for iMTFA configs for the NOVEL + ALL classes?

### ISSUE THREAD

**Issue by duynn912** [danganea/iMTFA#2]
Dear authors,

Thank you for your great work and your code.

I followed your instructions to re-run your code, but when I run iMTFA in novel phase, I found that the data is taken from 'coco_trainval_novel_1shot_seed9'. Would you please explain this setup. 
I want to know why seed_9 is chosen but not another seed? Is this seed 9 for your results reported in your paper.

Thank you in advance! I hope to hear your response soon.

Sincerely,
DuyNN

**Comment by danganea** [comment]
Hello!

Thank you for your interest!

Could you share the command you're using to run the code? I can then perhaps point you to the solution faster.

In general, all seeds and yaml scripts we have used are in:

`https://github.com/danganea/iMTFA/tree/main/configs/coco-experiments` 

Once the 'seed' folders are generated, `run_experiments.py`  runs the experiments 'for all seeds'. Otherwise, `run_train.py` only handles one training configuration and one output folder. 

To further alleviate your concerns regarding the fairness of the evaluation, you can have a look at:

https://1drv.ms/u/s!Ako0GB-Fly5dgaI6a9w7V7qGexkiiA?e=UUzeYV

the faster_rcnn folder has 'seed' folders which allow you to see both the config and the logs for each training. 

Waiting for your reply.

**Comment by danganea** [comment]
I think I understand what you mean:

There is a 'base' config here, for all configs:

`https://github.com/danganea/iMTFA/blob/main/configs/coco-experiments/mask_rcnn_R_50_FPN_ft_fullclsag_cos_bh_all_10shot.yaml` 

This one has one 'random' seed picked, seed9 for example. This just helped me to run the training in a 'simple' way, without having to aggregate it in 'run_experiments'.  It's just meant as a simple 'demo' or 'check' that the model runs.

The 'run_experiments' script replaces that 'seed9' value with the proper seed number for every seed in the range you specify (in our case, [0,9]

**Comment by duynn912** [comment]
@danganea thank you for your quick response!

I think I need a little time to have an insight in your training, then I will discuss with you if I have any further concerns.

Best regards,
DuyNN
